// Standalone compile target (maintainer decision: pulled forward from
// Phase 3 as a TEST build; the public release pipeline with SHA256SUMS
// publishing, attestations, and code signing remains Phase 3).
//
// What it does:
//   1. builds the web bundle (vite),
//   2. temporarily overwrites src/server/standalone-manifest.ts with
//      generated `with { type: "file" }` imports for every dist/web file
//      and every migration file, so `bun build --compile` embeds them,
//   3. compiles src/server/index.ts into a single-file executable per
//      requested target, printing a SHA-256 for each,
//   4. ALWAYS restores the committed manifest stub (finally), so the
//      working tree stays clean.
//
// Usage: bun run compile [--target linux-x64|windows-x64|darwin-arm64|
//        darwin-x64|all]  (default: linux-x64 and windows-x64)
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(fileURLToPath(new URL("..", import.meta.url)));
const MANIFEST_PATH = join(ROOT, "src/server/standalone-manifest.ts");
const WEB_DIST = join(ROOT, "dist/web");
const MIGRATIONS_ROOT = join(ROOT, "src/db/migrations");
const OUT_DIR = join(ROOT, "dist/bin");

const TARGETS: Record<string, { bun: string; suffix: string }> = {
  "linux-x64": { bun: "bun-linux-x64", suffix: "" },
  "windows-x64": { bun: "bun-windows-x64", suffix: ".exe" },
  "darwin-arm64": { bun: "bun-darwin-arm64", suffix: "" },
  "darwin-x64": { bun: "bun-darwin-x64", suffix: "" },
};

function run(command: string, args: string[]): void {
  const result = spawnSync(command, args, {
    cwd: ROOT,
    stdio: "inherit",
    shell: process.platform === "win32",
  });
  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} exited ${result.status}`);
  }
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

function toPosix(path: string): string {
  return path.split("\\").join("/");
}

/** Generated module: embedded-file imports plus the manifest object. */
function generateManifest(): string {
  const imports: string[] = [];
  const webEntries: string[] = [];
  const migrationEntries: string[] = [];
  let n = 0;

  for (const file of walk(WEB_DIST).sort()) {
    const urlPath = "/" + toPosix(relative(WEB_DIST, file));
    const importPath = "../../dist/web/" + toPosix(relative(WEB_DIST, file));
    const ident = `web${n++}`;
    imports.push(
      `import ${ident} from ${JSON.stringify(importPath)} with { type: "file" };`,
    );
    webEntries.push(`  ${JSON.stringify(urlPath)}: ${ident},`);
  }

  for (const engine of ["sqlite", "pg"]) {
    const dir = join(MIGRATIONS_ROOT, engine);
    for (const file of walk(dir).sort()) {
      const rel = toPosix(relative(MIGRATIONS_ROOT, file));
      // The migrator needs the .sql files and the journal; snapshots are
      // drizzle-kit development artifacts.
      if (!rel.endsWith(".sql") && !rel.endsWith("_journal.json")) continue;
      const importPath = "../db/migrations/" + rel;
      const ident = `mig${n++}`;
      imports.push(
        `import ${ident} from ${JSON.stringify(importPath)} with { type: "file" };`,
      );
      migrationEntries.push(`  ${JSON.stringify(rel)}: ${ident},`);
    }
  }

  return [
    "// GENERATED by scripts/compile.ts for a standalone build. If you are",
    "// seeing this in git status, a compile run failed before restoring",
    "// the stub: run `git checkout -- src/server/standalone-manifest.ts`.",
    ...imports,
    "",
    "export interface StandaloneManifest {",
    "  webAssets: Record<string, string>;",
    "  migrationFiles: Record<string, string>;",
    "}",
    "",
    "export const manifest: StandaloneManifest = {",
    "  webAssets: {",
    ...webEntries,
    "  },",
    "  migrationFiles: {",
    ...migrationEntries,
    "  },",
    "};",
    "",
  ].join("\n");
}

function parseTargets(): string[] {
  const flag = process.argv.indexOf("--target");
  const value = flag === -1 ? undefined : process.argv[flag + 1];
  if (value === undefined) return ["linux-x64", "windows-x64"];
  if (value === "all") return Object.keys(TARGETS);
  if (!(value in TARGETS)) {
    throw new Error(
      `unknown target ${value}; expected ${Object.keys(TARGETS).join(", ")} or all`,
    );
  }
  return [value];
}

const targets = parseTargets();
console.log(`[compile] building web bundle...`);
run("bun", ["run", "build"]);

const stub = readFileSync(MANIFEST_PATH, "utf8");
mkdirSync(OUT_DIR, { recursive: true });
try {
  writeFileSync(MANIFEST_PATH, generateManifest());
  for (const target of targets) {
    const spec = TARGETS[target];
    if (spec === undefined) continue;
    const outfile = join(OUT_DIR, `hatcheck-${target}${spec.suffix}`);
    console.log(`[compile] ${target} -> ${relative(ROOT, outfile)}`);
    run("bun", [
      "build",
      "--compile",
      `--target=${spec.bun}`,
      // Node-only fallbacks; never loaded under the Bun runtime, so the
      // native addons stay out of the binary (see password.ts and
      // store.sqlite.ts).
      "--external",
      "@node-rs/argon2",
      "--external",
      "better-sqlite3",
      "src/server/index.ts",
      "--outfile",
      outfile,
    ]);
    const digest = createHash("sha256")
      .update(readFileSync(outfile))
      .digest("hex");
    console.log(`[compile] sha256(${relative(ROOT, outfile)}) = ${digest}`);
  }
} finally {
  writeFileSync(MANIFEST_PATH, stub);
}
console.log("[compile] done; manifest stub restored");
